
minimaldepends:
	unzip -o dotnet-protobufs*.zip
	unzip -o FreeImage-*.zip
	unzip -o curl*.zip
	unzip -o boost*.zip
	unzip -o libantlr*.zip
	unzip -o ogre*.zip
	unzip -o SDL*.zip
	unzip -o IronPython*.zip
	unzip -o ois*.zip
	unzip -o mono*.zip
	unzip -o libmono*.zip
	unzip -o bullet*.zip
	unzip -o awesomium*.zip
	unzip -o sqlite*.zip

depends: minimaldepends

fulldepends: depends

