
minimaldepends:
	unzip dotnet-protobufs*.zip
	unzip FreeImage-*.zip
	unzip curl*.zip
	unzip boost*.zip
	unzip ogre*.zip
	unzip SDL*.zip
	unzip ois*.zip
	unzip bullet*.zip

depends: minimaldepends

fulldepends: depends

