#!/bin/bash

dir=`pwd`

if test  $# = "1"
then
NUMPROCS="-j6"
echo $NUMPROCS
else
NUMPROCS=$2
echo $NUMPROCS
fi

#######################################
# Install dotnet-protobufs            #
#######################################
echo "Installing dotnet-protobufs..."
tar -zxf dotnet-protobufs.f0b299db576712173d00cacf0fd7c7583eb8ed25.tar.gz
cd ${dir}/dotnet-protobufs
patch -p1 < ../protobufs_patches/build_fix.patch
patch -p1 < ../protobufs_patches/csharp_generator_generic_namespace_alias.patch
./autogen.sh
./configure --prefix=${dir}/protobufs
make $NUMPROCS
make install
cd ..
