#!/bin/bash

#######################################
# Check for superuser                 #
#######################################
while test $UID != "0" ; do
    echo "Please run this script with sudo."
    echo "Usage: sudo ./install my_username -j6"
    echo "Where -j6 indicates you have 6 processors"
    exit;
done

while test $# = "0" ; do
    echo "Please run this script with sudo."
    echo "Usage: sudo ./install my_username -j6"
    echo "Where -j6 indicates you have 6 processors"
    exit;
done

usr=$1
dir=`pwd`
if test  $# = "1"
then
NUMPROCS="-j6"
echo $NUMPROCS
else
NUMPROCS=$2
echo $NUMPROCS
fi

apt-get install unzip zip automake1.9 nvidia-cg-toolkit jam libcurl4-openssl-dev g++ libzzip-dev libxt-dev libxaw7-dev libxxf86vm-dev libxrandr-dev libfreetype6-dev autoconf libtool libpcre3-dev flex bison patch libbz2-dev gawk

#######################################
# Install Boost 1.35                  #
#######################################
if apt-get install libboost-system1.38-dev || apt-get install libboost-system1.37-dev || apt-get install libboost-system1.36-dev || apt-get install libboost-system1.35-dev; then
apt-get install libboost-program_options1.38-dev || apt-get install libboost-program_options1.37-dev || apt-get install libboost-program_options1.36-dev || apt-get install libboost-program_options1.35-dev
apt-get install libboost-thread1.38-dev || apt-get install libboost-thread1.37-dev || apt-get install libboost-thread1.36-dev || apt-get install libboost-thread1.35-dev
else
echo $NUMPROCS
tar -zxf boost_1_35_0.tar.gz
su -c "cd ${dir}/boost_1_35_0;./configure; cat Makefile |sed -e s/LIBS=$/LIBS=$NUMPROCS/ > Makefilej6 ;make $NUMPROCS -f Makefilej6" - $usr
cd boost_1_35_0
make install
cd ..
fi
#######################################
# Install FreeImage                   #
#######################################


if apt-cache show libfreeimge-dev | grep 3\\.9 || ! apt-cache show libfreeimage-dev; then
echo "Installing FreeImage..."
su -c "yes A|unzip ${dir}/FreeImage3100.zip -d $dir" - $usr
su -c "cd ${dir};cd FreeImage;patch -p1 < ../FreeImage64bit.patch;make $NUMPROCS;" - $usr
cd ${dir}/FreeImage
make install
cd ..
else
apt-get install libfreeimage-dev
fi

#######################################
# Install dotnet-protobufs            #
#######################################
echo "Installing dotnet-protobufs..."
su -c "cd ${dir};./protobufs_install $NUMPROCS" - $usr
